#!/bin/bash
set -e

PWDPARAM="'$DB_PASS'"

echo setting user and database $DB_NAME
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $DB_USER WITH SUPERUSER PASSWORD $DB_PASS;
    CREATE DATABASE $DB_NAME OWNER $DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
EOSQL